# Generated by Django 2.2.7 on 2020-11-08 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile_Company',
            fields=[
                ('company_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=32)),
                ('is_indian', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Mobile_Model',
            fields=[
                ('model_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=32)),
                ('internal_id', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mobile.Mobile_Company')),
            ],
        ),
    ]
