# Generated by Django 2.2.7 on 2020-11-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mobile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile_model',
            name='internal_id',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
