# Generated by Django 2.2.7 on 2020-11-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mobile', '0002_auto_20201108_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile_model',
            name='model_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
