# Generated by Django 2.2.7 on 2020-11-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mobile', '0003_auto_20201108_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile_company',
            name='company_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
