# Generated by Django 2.2.7 on 2020-11-08 11:43

import Mobile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mobile', '0004_auto_20201108_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile_model',
            name='internal_id',
            field=models.CharField(default=Mobile.models.Mobile_Model.number, max_length=32),
        ),
    ]
